name: fast_vpn
description: A vpn application by Programming Wormhole
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State managment
  get: ^4.6.6

  # SVG
  flutter_svg:

  # Lottie Animation
  lottie:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Assets Generator
  build_runner:
  flutter_gen_runner:
# To auto gen assets path follow the below command
# fluttergen -c pubspec.yaml

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/animations/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Black.ttf
          weight: 900
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist/Urbanist-Thin.ttf
          weight: 100
